[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "alembic upgrade head && honcho start"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
