"""sync_schema_with_models

Revision ID: 0f985a5b0ec0
Revises: 20260328_0002
Create Date: 2026-03-28 13:00:34.080176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f985a5b0ec0'
down_revision: Union[str, None] = '20260328_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_snapshots_tenant_id'), table_name='stock_snapshots')
    op.drop_table('stock_snapshots')
    op.drop_constraint(op.f('uq_business_profiles_tenant_id'), 'business_profiles', type_='unique')
    op.create_index(op.f('ix_business_profiles_tenant_id'), 'business_profiles', ['tenant_id'], unique=True)
    op.drop_constraint(op.f('business_snapshots_heuristic_ruleset_id_fkey'), 'business_snapshots', type_='foreignkey')
    op.drop_column('business_snapshots', 'heuristic_ruleset_id')
    op.add_column('decision_audit_log', sa.Column('decision_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))
    op.add_column('decision_audit_log', sa.Column('triggered_by', sa.String(length=100), nullable=False))
    op.add_column('decision_audit_log', sa.Column('actor_user_id', sa.UUID(), nullable=True))
    op.add_column('decision_audit_log', sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.alter_column('decision_audit_log', 'decision_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_decision_audit_log_tenant_created_at_desc'), table_name='decision_audit_log')
    op.create_index(op.f('ix_decision_audit_log_tenant_id'), 'decision_audit_log', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('decision_audit_log_source_ruleset_id_fkey'), 'decision_audit_log', type_='foreignkey')
    op.drop_constraint(op.f('decision_audit_log_source_snapshot_id_fkey'), 'decision_audit_log', type_='foreignkey')
    op.create_foreign_key(None, 'decision_audit_log', 'users', ['actor_user_id'], ['user_id'], ondelete='SET NULL')
    op.drop_column('decision_audit_log', 'output_json')
    op.drop_column('decision_audit_log', 'input_state_json')
    op.drop_column('decision_audit_log', 'displayed_to_user')
    op.drop_column('decision_audit_log', 'user_acknowledged')
    op.drop_column('decision_audit_log', 'confidence_level')
    op.drop_column('decision_audit_log', 'source_ruleset_id')
    op.drop_column('decision_audit_log', 'source_snapshot_id')
    op.add_column('expense_entries', sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('expense_entries', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('expense_entries', sa.Column('transaction_date', sa.Date(), nullable=False))
    op.add_column('expense_entries', sa.Column('description', sa.String(length=500), nullable=False))
    op.add_column('expense_entries', sa.Column('is_recurring', sa.Boolean(), nullable=False))
    op.add_column('expense_entries', sa.Column('payment_method', sa.String(length=30), nullable=False))
    op.add_column('expense_entries', sa.Column('supplier_name', sa.String(length=300), nullable=True))
    op.create_index(op.f('ix_expense_entries_transaction_date'), 'expense_entries', ['transaction_date'], unique=False)
    op.drop_column('expense_entries', 'amount_ars')
    op.drop_column('expense_entries', 'expense_date')
    op.drop_column('expense_entries', 'source_type')
    op.drop_column('expense_entries', 'category_code')
    op.add_column('health_score_snapshots', sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('health_score_snapshots', sa.Column('level', sa.String(length=20), nullable=False))
    op.add_column('health_score_snapshots', sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))
    op.add_column('health_score_snapshots', sa.Column('triggered_by', sa.String(length=100), nullable=False))
    op.add_column('health_score_snapshots', sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('health_score_snapshots', sa.Column('confidence_level', sa.String(length=20), nullable=True))
    op.add_column('health_score_snapshots', sa.Column('data_completeness_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.alter_column('health_score_snapshots', 'heuristic_version',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True,
               existing_server_default=sa.text("'v1'::text"))
    op.alter_column('health_score_snapshots', 'primary_risk_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_health_score_snapshots_tenant_created_at_desc'), table_name='health_score_snapshots')
    op.create_index(op.f('ix_health_score_snapshots_source_snapshot_id'), 'health_score_snapshots', ['source_snapshot_id'], unique=False)
    op.create_index(op.f('ix_health_score_snapshots_tenant_id'), 'health_score_snapshots', ['tenant_id'], unique=False)
    op.drop_column('health_score_snapshots', 'score_total')
    op.drop_column('health_score_snapshots', 'score_version')
    op.drop_column('health_score_snapshots', 'score_confidence')
    op.add_column('heuristic_rule_sets', sa.Column('vertical', sa.String(length=50), nullable=True))
    op.add_column('heuristic_rule_sets', sa.Column('version', sa.String(length=20), nullable=True))
    op.add_column('heuristic_rule_sets', sa.Column('rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.execute("UPDATE heuristic_rule_sets SET vertical = vertical_code, version = version_code, rules = rules_json")
    op.alter_column('heuristic_rule_sets', 'vertical', nullable=False)
    op.alter_column('heuristic_rule_sets', 'version', nullable=False)
    op.alter_column('heuristic_rule_sets', 'rules', nullable=False)
    op.drop_constraint(op.f('uq_heuristic_rule_sets_version_code'), 'heuristic_rule_sets', type_='unique')
    op.create_index(op.f('ix_heuristic_rule_sets_vertical'), 'heuristic_rule_sets', ['vertical'], unique=False)
    op.drop_column('heuristic_rule_sets', 'version_code')
    op.drop_column('heuristic_rule_sets', 'vertical_code')
    op.drop_column('heuristic_rule_sets', 'rules_json')
    op.add_column('notifications', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('body', sa.Text(), nullable=False))
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=50), nullable=False))
    op.add_column('notifications', sa.Column('channel', sa.String(length=30), nullable=False))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.alter_column('notifications', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('notifications', 'delivery_status')
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'channel_code')
    op.drop_column('notifications', 'message')
    op.add_column('products', sa.Column('sku', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('products', 'sale_price_ars',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('products', 'unit_cost_ars',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('products', 'stock_units',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'low_stock_threshold_units',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('products', 'source_type')
    op.add_column('sales_entries', sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('sales_entries', sa.Column('transaction_date', sa.Date(), nullable=False))
    op.add_column('sales_entries', sa.Column('payment_method', sa.String(length=30), nullable=False))
    op.drop_index(op.f('ix_sales_entries_tenant_sale_date_desc'), table_name='sales_entries')
    op.create_index(op.f('ix_sales_entries_tenant_id'), 'sales_entries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sales_entries_transaction_date'), 'sales_entries', ['transaction_date'], unique=False)
    op.drop_column('sales_entries', 'gross_amount_ars')
    op.drop_column('sales_entries', 'sale_source_type')
    op.drop_column('sales_entries', 'sale_date')
    op.drop_column('sales_entries', 'unit_price_ars')
    op.drop_constraint(op.f('uq_subscriptions_tenant_id'), 'subscriptions', type_='unique')
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.add_column('uploaded_files', sa.Column('uploaded_by', sa.UUID(), nullable=True))
    op.add_column('uploaded_files', sa.Column('original_filename', sa.String(length=500), nullable=False))
    op.add_column('uploaded_files', sa.Column('s3_key', sa.String(length=1000), nullable=False))
    op.add_column('uploaded_files', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.add_column('uploaded_files', sa.Column('size_bytes', sa.BigInteger(), nullable=False))
    op.add_column('uploaded_files', sa.Column('purpose', sa.String(length=50), nullable=False))
    op.add_column('uploaded_files', sa.Column('status', sa.String(length=30), nullable=False))
    op.alter_column('uploaded_files', 'processing_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_foreign_key(None, 'uploaded_files', 'users', ['uploaded_by'], ['user_id'], ondelete='SET NULL')
    op.drop_column('uploaded_files', 'storage_key')
    op.drop_column('uploaded_files', 'file_type')
    op.alter_column('user_activity_events', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('user_activity_events_user_id_fkey'), 'user_activity_events', type_='foreignkey')
    op.create_foreign_key(None, 'user_activity_events', 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
    op.add_column('weekly_score_history', sa.Column('week_start', sa.Date(), nullable=False))
    op.add_column('weekly_score_history', sa.Column('week_end', sa.Date(), nullable=False))
    op.add_column('weekly_score_history', sa.Column('avg_score', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('weekly_score_history', sa.Column('min_score', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('weekly_score_history', sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('weekly_score_history', sa.Column('level', sa.String(length=20), nullable=False))
    op.alter_column('weekly_score_history', 'trend_label',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_weekly_score_history_tenant_week_start_desc'), table_name='weekly_score_history')
    op.create_index(op.f('ix_weekly_score_history_tenant_id'), 'weekly_score_history', ['tenant_id'], unique=False)
    op.drop_column('weekly_score_history', 'week_start_date')
    op.drop_column('weekly_score_history', 'score_stock')
    op.drop_column('weekly_score_history', 'delta_vs_previous_week')
    op.drop_column('weekly_score_history', 'health_score_total')
    op.drop_column('weekly_score_history', 'score_margin')
    op.drop_column('weekly_score_history', 'score_supplier')
    op.drop_column('weekly_score_history', 'score_cash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_score_history', sa.Column('score_cash', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('weekly_score_history', sa.Column('score_supplier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('weekly_score_history', sa.Column('score_margin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('weekly_score_history', sa.Column('health_score_total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('weekly_score_history', sa.Column('delta_vs_previous_week', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('weekly_score_history', sa.Column('score_stock', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('weekly_score_history', sa.Column('week_start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_weekly_score_history_tenant_id'), table_name='weekly_score_history')
    op.create_index(op.f('ix_weekly_score_history_tenant_week_start_desc'), 'weekly_score_history', ['tenant_id', sa.literal_column('week_start_date DESC')], unique=False)
    op.alter_column('weekly_score_history', 'trend_label',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('weekly_score_history', 'level')
    op.drop_column('weekly_score_history', 'max_score')
    op.drop_column('weekly_score_history', 'min_score')
    op.drop_column('weekly_score_history', 'avg_score')
    op.drop_column('weekly_score_history', 'week_end')
    op.drop_column('weekly_score_history', 'week_start')
    op.drop_constraint(None, 'user_activity_events', type_='foreignkey')
    op.create_foreign_key(op.f('user_activity_events_user_id_fkey'), 'user_activity_events', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('user_activity_events', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('uploaded_files', sa.Column('file_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('uploaded_files', sa.Column('storage_key', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'uploaded_files', type_='foreignkey')
    op.alter_column('uploaded_files', 'processing_status',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('uploaded_files', 'status')
    op.drop_column('uploaded_files', 'purpose')
    op.drop_column('uploaded_files', 'size_bytes')
    op.drop_column('uploaded_files', 'content_type')
    op.drop_column('uploaded_files', 's3_key')
    op.drop_column('uploaded_files', 'original_filename')
    op.drop_column('uploaded_files', 'uploaded_by')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.create_unique_constraint(op.f('uq_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], postgresql_nulls_not_distinct=False)
    op.add_column('sales_entries', sa.Column('unit_price_ars', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('sales_entries', sa.Column('sale_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('sales_entries', sa.Column('sale_source_type', sa.TEXT(), server_default=sa.text("'MANUAL'::text"), autoincrement=False, nullable=False))
    op.add_column('sales_entries', sa.Column('gross_amount_ars', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sales_entries_transaction_date'), table_name='sales_entries')
    op.drop_index(op.f('ix_sales_entries_tenant_id'), table_name='sales_entries')
    op.create_index(op.f('ix_sales_entries_tenant_sale_date_desc'), 'sales_entries', ['tenant_id', sa.literal_column('sale_date DESC')], unique=False)
    op.drop_column('sales_entries', 'payment_method')
    op.drop_column('sales_entries', 'transaction_date')
    op.drop_column('sales_entries', 'amount')
    op.add_column('products', sa.Column('source_type', sa.TEXT(), server_default=sa.text("'MANUAL'::text"), autoincrement=False, nullable=False))
    op.alter_column('products', 'low_stock_threshold_units',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'stock_units',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'unit_cost_ars',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'sale_price_ars',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('products', 'description')
    op.drop_column('products', 'sku')
    op.add_column('notifications', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('channel_code', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('delivery_status', sa.TEXT(), server_default=sa.text("'PENDING'::text"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.alter_column('notifications', 'title',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('notifications', 'metadata')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'channel')
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'body')
    op.drop_column('notifications', 'user_id')
    op.add_column('heuristic_rule_sets', sa.Column('rules_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('heuristic_rule_sets', sa.Column('vertical_code', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('heuristic_rule_sets', sa.Column('version_code', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_heuristic_rule_sets_vertical'), table_name='heuristic_rule_sets')
    op.create_unique_constraint(op.f('uq_heuristic_rule_sets_version_code'), 'heuristic_rule_sets', ['version_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('heuristic_rule_sets', 'rules')
    op.drop_column('heuristic_rule_sets', 'version')
    op.drop_column('heuristic_rule_sets', 'vertical')
    op.add_column('health_score_snapshots', sa.Column('score_confidence', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('health_score_snapshots', sa.Column('score_version', sa.TEXT(), server_default=sa.text("'v1a'::text"), autoincrement=False, nullable=False))
    op.add_column('health_score_snapshots', sa.Column('score_total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_health_score_snapshots_tenant_id'), table_name='health_score_snapshots')
    op.drop_index(op.f('ix_health_score_snapshots_source_snapshot_id'), table_name='health_score_snapshots')
    op.create_index(op.f('ix_health_score_snapshots_tenant_created_at_desc'), 'health_score_snapshots', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('health_score_snapshots', 'primary_risk_code',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('health_score_snapshots', 'heuristic_version',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'v1'::text"))
    op.drop_column('health_score_snapshots', 'data_completeness_score')
    op.drop_column('health_score_snapshots', 'confidence_level')
    op.drop_column('health_score_snapshots', 'snapshot_date')
    op.drop_column('health_score_snapshots', 'triggered_by')
    op.drop_column('health_score_snapshots', 'dimensions')
    op.drop_column('health_score_snapshots', 'level')
    op.drop_column('health_score_snapshots', 'total_score')
    op.add_column('expense_entries', sa.Column('category_code', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('expense_entries', sa.Column('source_type', sa.TEXT(), server_default=sa.text("'MANUAL'::text"), autoincrement=False, nullable=False))
    op.add_column('expense_entries', sa.Column('expense_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('expense_entries', sa.Column('amount_ars', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_expense_entries_transaction_date'), table_name='expense_entries')
    op.drop_column('expense_entries', 'supplier_name')
    op.drop_column('expense_entries', 'payment_method')
    op.drop_column('expense_entries', 'is_recurring')
    op.drop_column('expense_entries', 'description')
    op.drop_column('expense_entries', 'transaction_date')
    op.drop_column('expense_entries', 'category')
    op.drop_column('expense_entries', 'amount')
    op.add_column('decision_audit_log', sa.Column('source_snapshot_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('decision_audit_log', sa.Column('source_ruleset_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('decision_audit_log', sa.Column('confidence_level', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('decision_audit_log', sa.Column('user_acknowledged', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('decision_audit_log', sa.Column('displayed_to_user', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('decision_audit_log', sa.Column('input_state_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('decision_audit_log', sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'decision_audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('decision_audit_log_source_snapshot_id_fkey'), 'decision_audit_log', 'business_snapshots', ['source_snapshot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('decision_audit_log_source_ruleset_id_fkey'), 'decision_audit_log', 'heuristic_rule_sets', ['source_ruleset_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_decision_audit_log_tenant_id'), table_name='decision_audit_log')
    op.create_index(op.f('ix_decision_audit_log_tenant_created_at_desc'), 'decision_audit_log', ['tenant_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('decision_audit_log', 'decision_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('decision_audit_log', 'context')
    op.drop_column('decision_audit_log', 'actor_user_id')
    op.drop_column('decision_audit_log', 'triggered_by')
    op.drop_column('decision_audit_log', 'decision_data')
    op.add_column('business_snapshots', sa.Column('heuristic_ruleset_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('business_snapshots_heuristic_ruleset_id_fkey'), 'business_snapshots', 'heuristic_rule_sets', ['heuristic_ruleset_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_business_profiles_tenant_id'), table_name='business_profiles')
    op.create_unique_constraint(op.f('uq_business_profiles_tenant_id'), 'business_profiles', ['tenant_id'], postgresql_nulls_not_distinct=False)
    op.create_table('stock_snapshots',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_sku_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock_value_est', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('critical_stock_value_est', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('stock_snapshots_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_snapshots_pkey'))
    )
    op.create_index(op.f('ix_stock_snapshots_tenant_id'), 'stock_snapshots', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
