"""ORM model: decision_audit_log."""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, ForeignKey, Integer, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.observability.trace import get_trace_id
from app.persistence.db.base import PGJSONB, Base, UUIDPrimaryKeyMixin


class DecisionAuditLog(UUIDPrimaryKeyMixin, Base):
    """
    Immutable log of every decision generated by the Health Engine or rules.
    Insert-only — never updated or deleted.
    """

    __tablename__ = "decision_audit_log"

    #: NULLABLE desde la migración ``20260806_0003``. Casi todas las decisiones
    #: del sistema pertenecen a un tenant, pero las del flujo de solicitudes de
    #: acceso (crear, verificar el email, rechazar, poner en lista de espera)
    #: ocurren ANTES de que exista ningún tenant — y son justamente las que hay
    #: que poder auditar. ``approve()`` sí graba el tenant, porque para cuando
    #: escribe la decisión ya lo acuñó en la misma transacción.
    tenant_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.tenant_id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    decision_type: Mapped[str] = mapped_column(String(100), nullable=False)
    decision_data: Mapped[dict[str, Any]] = mapped_column(PGJSONB, nullable=False)
    triggered_by: Mapped[str] = mapped_column(String(100), nullable=False)
    actor_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.user_id", ondelete="SET NULL"),
        nullable=True,
    )
    context: Mapped[dict[str, Any] | None] = mapped_column(PGJSONB, nullable=True)
    # Correlación transversal: autocapturado del request vigente en cada INSERT ORM.
    trace_id: Mapped[str | None] = mapped_column(
        String(64), nullable=True, default=lambda: get_trace_id()
    )
    tokens_input: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    tokens_output: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    tokens_total: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    def __repr__(self) -> str:
        return (
            f"<DecisionAuditLog tenant={self.tenant_id}"
            f" type={self.decision_type!r} at={self.created_at}>"
        )
