"""ORM model: decision_audit_log."""

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, ForeignKey, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.persistence.db.base import PGJSONB, Base, UUIDPrimaryKeyMixin


class DecisionAuditLog(UUIDPrimaryKeyMixin, Base):
    """
    Immutable log of every decision generated by the Health Engine or rules.
    Insert-only — never updated or deleted.
    """

    __tablename__ = "decision_audit_log"

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.tenant_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    decision_type: Mapped[str] = mapped_column(String(100), nullable=False)
    decision_data: Mapped[dict[str, Any]] = mapped_column(PGJSONB, nullable=False)
    triggered_by: Mapped[str] = mapped_column(String(100), nullable=False)
    actor_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.user_id", ondelete="SET NULL"),
        nullable=True,
    )
    context: Mapped[dict[str, Any] | None] = mapped_column(PGJSONB, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    def __repr__(self) -> str:
        return (
            f"<DecisionAuditLog tenant={self.tenant_id}"
            f" type={self.decision_type!r} at={self.created_at}>"
        )
